name: Pipeline

on:
  push:
    branches:
      - "*"

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Postgre Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/postgre:v${{ github.run_number }} -f DockerDB/Dockerfile .

      - name: Build App Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/app:v${{ github.run_number }} .

      - name: Push App Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/app:v${{ github.run_number }}

      - name: Push Postgre Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/postgre:v${{ github.run_number }}

  update:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kubernetes repo
        uses: actions/checkout@v3
        with:
          repository: 'anadokaza/DevOpsProjects'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Modify image tags in manifests
        run: |
          git config user.email "ana.dokaza@gmail.com"
          git config user.name "anadokaza"
          sed -i "s+ana707/app.*+${{ secrets.DOCKER_USERNAME }}/app:v${{ github.run_number }}+g" deployment.yaml
          sed -i "s+ana707/postgre.*+${{ secrets.DOCKER_USERNAME }}/postgre:v${{ github.run_number }}+g" statefulset.yaml
          git add .
          git commit -m "Updated Docker image tags to v${{ github.run_number }}"
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}